"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import mimetypes
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError("DJANGO_SECRET_KEY must be set in production.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "").lower() in ("1", "true", "yes")
ENVIRONMENT = os.environ.get("DJANGO_ENV", "prod").lower()

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    "ca_practice.apps.CaPracticeConfig",
    "ca_practice_control_group_gpt_freestyle.apps.CaPracticeControlGroupConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # "ca_practice",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "mysite.copy_protection.DisableCopyMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "mysite.access_control.AppAccessControlMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "mysite.logging.RequestContextMiddleware",
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "libraries": {
                # Explicitly register our custom template filters so Django
                # can find them even if app autodiscovery misses them in some
                # environments (e.g., non-standard PYTHONPATH setups).
                "ca_practice_extras": "ca_practice.templatetags.ca_practice_extras",
            },
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.environ.get("DJANGO_SQLITE_PATH", str(BASE_DIR / "db.sqlite3")),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Zurich"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

mimetypes.add_type("text/javascript", ".jsx", True)

BASE_PATH = os.environ.get("APP_BASE_PATH", "/projects/calsa-webapp").rstrip("/")
if BASE_PATH:
    STATIC_URL = f"{BASE_PATH}/static/"
    LOGIN_URL = f"{BASE_PATH}/"
else:
    STATIC_URL = "static/"

# Keep auth/CSRF cookies scoped to this app path so parallel deployments
# on the same domain do not overwrite each other's cookies.
COOKIE_PATH = f"{BASE_PATH}/" if BASE_PATH else "/"
SESSION_COOKIE_PATH = COOKIE_PATH
CSRF_COOKIE_PATH = COOKIE_PATH
SESSION_COOKIE_NAME = os.environ.get("DJANGO_SESSION_COOKIE_NAME", "sessionid")
CSRF_COOKIE_NAME = os.environ.get("DJANGO_CSRF_COOKIE_NAME", "csrftoken")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = LOGIN_URL if BASE_PATH else "login"  # name used by auth.urls
LOGIN_REDIRECT_URL = "ca_practice:task_session"  # where to go after successful login
LOGOUT_REDIRECT_URL = LOGIN_URL if BASE_PATH else "login"  # after logout
DEFAULT_FROM_EMAIL = os.environ.get("DJANGO_DEFAULT_FROM_EMAIL", "noreply@localhost")
EMAIL_BACKEND = os.environ.get(
    "DJANGO_EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = os.environ.get("DJANGO_EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("DJANGO_EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("DJANGO_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("DJANGO_EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("DJANGO_EMAIL_USE_TLS", "1").lower() in ("1", "true", "yes")
EMAIL_USE_SSL = os.environ.get("DJANGO_EMAIL_USE_SSL", "0").lower() in ("1", "true", "yes")

if not DEBUG and ENVIRONMENT == "prod":
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Logging
LOG_LEVEL = os.environ.get("DJANGO_LOG_LEVEL", "INFO").upper()
LOG_TO = os.environ.get("DJANGO_LOG_TO", "console").lower()
LOG_FILE = os.environ.get("DJANGO_LOG_FILE", str(BASE_DIR / "logs" / "django.log"))
LOG_FILE_MODE = os.environ.get("DJANGO_LOG_FILE_MODE", "append").lower()
LOG_FORMAT = os.environ.get("DJANGO_LOG_FORMAT", "text").lower()

LOG_HANDLERS: list[str] = []
LOGGING_HANDLERS = {}

if LOG_TO in ("file", "both"):
    os.makedirs(Path(LOG_FILE).parent, exist_ok=True)
    LOG_HANDLERS.append("file")
    file_handler_class = "logging.FileHandler"
    file_handler_mode = "a"
    if LOG_FILE_MODE == "overwrite":
        file_handler_mode = "w"
    LOGGING_HANDLERS["file"] = {
        "level": LOG_LEVEL,
        "class": file_handler_class,
        "filename": LOG_FILE,
        "mode": file_handler_mode,
        "formatter": "verbose",
    }

if LOG_TO in ("console", "both"):
    LOG_HANDLERS.append("console")
    LOGGING_HANDLERS["console"] = {
        "level": LOG_LEVEL,
        "class": "logging.StreamHandler",
        "formatter": "verbose",
    }


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "()": "mysite.logging.ZurichFormatter",
            "format": "%(asctime)s [%(levelname)s] %(name)s %(request_id)s %(user)s: %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S %z",
        },
        "json": {
            "()": "mysite.logging.ZurichJsonFormatter",
        },
    },
    "handlers": LOGGING_HANDLERS,
    "root": {
        "handlers": LOG_HANDLERS or ["console"],
        "level": LOG_LEVEL,
    },
    "filters": {
        "request_context": {
            "()": "mysite.logging.RequestContextFilter",
        }
    },
}

# Attach request context to all handlers.
for _handler in LOGGING_HANDLERS.values():
    _handler.setdefault("filters", []).append("request_context")
    _handler["formatter"] = "json" if LOG_FORMAT == "jsonl" else "verbose"
